# Generated by Django 4.2.7 on 2025-09-24 21:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('associations', '0003_remove_logement_unique_logement_association_and_more'),
        ('cotisations', '0002_add_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotisation',
            options={'ordering': ['-periode', '-date_creation'], 'verbose_name': 'Cotisation', 'verbose_name_plural': 'Cotisations'},
        ),
        migrations.RemoveConstraint(
            model_name='cotisation',
            name='unique_cotisation_periode',
        ),
        migrations.AddField(
            model_name='cotisation',
            name='cree_par',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='date_modification',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description/Note'),
        ),
        migrations.AddField(
            model_name='typecotisation',
            name='cree_par',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='typecotisation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant (DA)'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='periode',
            field=models.DateField(verbose_name='Période (mois/trimestre/année)'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='statut',
            field=models.CharField(choices=[('due', 'Due'), ('payee', 'Payée'), ('retard', 'En retard'), ('annulee', 'Annulée')], default='due', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='type_cotisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotisations.typecotisation', verbose_name='Type de cotisation'),
        ),
        migrations.AlterField(
            model_name='typecotisation',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Type actif'),
        ),
        migrations.AlterField(
            model_name='typecotisation',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant (DA)'),
        ),
        migrations.AlterField(
            model_name='typecotisation',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Nom du type'),
        ),
        migrations.AlterField(
            model_name='typecotisation',
            name='periodicite',
            field=models.CharField(choices=[('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle')], max_length=15, verbose_name='Périodicité'),
        ),
        migrations.AlterUniqueTogether(
            name='cotisation',
            unique_together={('logement', 'type_cotisation', 'periode')},
        ),
        migrations.AlterUniqueTogether(
            name='typecotisation',
            unique_together={('association', 'nom')},
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['statut', 'date_echeance'], name='iltizem_cot_statut_b4b598_idx'),
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['logement', 'periode'], name='iltizem_cot_logemen_cbef4f_idx'),
        ),
    ]
