# Generated by Django 4.2.7 on 2025-09-24 21:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0003_alter_cotisation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paiements', '0002_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('annulation', 'Annulation')], max_length=15, verbose_name='Action')),
                ('anciennes_donnees', models.JSONField(blank=True, null=True, verbose_name='Anciennes données')),
                ('nouvelles_donnees', models.JSONField(blank=True, null=True, verbose_name='Nouvelles données')),
                ('raison', models.TextField(blank=True, verbose_name='Raison de la modification')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
            ],
            options={
                'verbose_name': 'Historique de paiement',
                'verbose_name_plural': 'Historiques des paiements',
                'db_table': 'iltizem_historique_paiements',
                'ordering': ['-date_action'],
            },
        ),
        migrations.AddField(
            model_name='paiement',
            name='numero_recu',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Numéro de reçu'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='cotisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='cotisations.cotisation', verbose_name='Cotisation payée'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateField(verbose_name='Date du paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('carte', 'Carte bancaire'), ('en_ligne', 'Paiement en ligne'), ('compensation', 'Compensation')], max_length=15, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant payé (DA)'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes/Commentaires'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence (N° chèque, virement, etc.)'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date_paiement', 'methode'], name='iltizem_pai_date_pa_1fb7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['enregistre_par', 'date_enregistrement'], name='iltizem_pai_enregis_85f64b_idx'),
        ),
        migrations.AddField(
            model_name='historiquepaiement',
            name='effectue_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par'),
        ),
        migrations.AddField(
            model_name='historiquepaiement',
            name='paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='paiements.paiement', verbose_name='Paiement'),
        ),
    ]
