# Generated by Django 4.2.7 on 2025-09-24 21:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('associations', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='logement',
            name='unique_logement_association',
        ),
        migrations.RemoveConstraint(
            model_name='logement',
            name='unique_resident_logement',
        ),
        migrations.AddField(
            model_name='association',
            name='admins_secondaires',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'admin_association'}, related_name='associations_secondaires', to=settings.AUTH_USER_MODEL, verbose_name='Administrateurs secondaires'),
        ),
        migrations.AddField(
            model_name='association',
            name='date_modification',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='association',
            name='montant_cotisation_defaut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant cotisation par défaut (DA)'),
        ),
        migrations.AddField(
            model_name='logement',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Logement actif'),
        ),
        migrations.AddField(
            model_name='logement',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='logement',
            name='date_modification',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='logement',
            name='etage',
            field=models.CharField(blank=True, max_length=10, verbose_name='Étage'),
        ),
        migrations.AddField(
            model_name='logement',
            name='montant_cotisation_personnalise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant cotisation personnalisé (DA)'),
        ),
        migrations.AddField(
            model_name='logement',
            name='nombre_pieces',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Nombre de pièces'),
        ),
        migrations.AlterField(
            model_name='association',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Association active'),
        ),
        migrations.AlterField(
            model_name='association',
            name='admin_principal',
            field=models.OneToOneField(limit_choices_to={'role': 'admin_association'}, on_delete=django.db.models.deletion.CASCADE, related_name='association_geree', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur principal'),
        ),
        migrations.AlterField(
            model_name='association',
            name='adresse',
            field=models.TextField(verbose_name='Adresse complète'),
        ),
        migrations.AlterField(
            model_name='association',
            name='nom',
            field=models.CharField(max_length=100, verbose_name="Nom de l'association"),
        ),
        migrations.AlterField(
            model_name='association',
            name='nombre_logements',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Nombre de logements'),
        ),
        migrations.AlterField(
            model_name='association',
            name='plan',
            field=models.CharField(choices=[('basique', 'Basique'), ('silver', 'Silver'), ('gold', 'Gold')], default='basique', max_length=10, verbose_name="Plan d'abonnement"),
        ),
        migrations.AlterField(
            model_name='logement',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Numéro/Nom du logement'),
        ),
        migrations.AlterField(
            model_name='logement',
            name='resident',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'resident'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logement', to=settings.AUTH_USER_MODEL, verbose_name='Résident'),
        ),
        migrations.AlterField(
            model_name='logement',
            name='superficie',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Surface (m²)'),
        ),
        migrations.AlterUniqueTogether(
            name='logement',
            unique_together={('association', 'numero')},
        ),
    ]
