# Generated by Django 4.2.7 on 2025-09-24 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('associations', '0003_remove_logement_unique_logement_association_and_more'),
        ('notifications', '0002_add_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Log de notification', 'verbose_name_plural': 'Logs de notifications'},
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'ordering': ['type_notification', 'nom'], 'verbose_name': 'Template de notification', 'verbose_name_plural': 'Templates de notification'},
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='contenu',
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='canal',
            field=models.CharField(default='email', max_length=10, verbose_name='Canal utilisé'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='date_programmee',
            field=models.DateTimeField(null=True, verbose_name='Date programmée'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='email_destinataire',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='message',
            field=models.TextField(null=True, verbose_name='Message envoyé'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='telephone_destinataire',
            field=models.CharField(blank=True, max_length=15, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='tentatives',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de tentatives'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='canal',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email + SMS')], default='email', max_length=10, verbose_name="Canal d'envoi"),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='cree_par',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='date_modification',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='envoyer_automatiquement',
            field=models.BooleanField(default=False, verbose_name='Envoi automatique'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='message',
            field=models.TextField(help_text='Variables disponibles: {{nom}}, {{montant}}, {{periode}}, {{date_echeance}}, {{association}}', null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_log', to='associations.association', verbose_name='Association'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='date_envoi',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='destinataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='envoye_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Envoyé par'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('erreur', 'Erreur'), ('annule', 'Annulé')], default='en_attente', max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='type_notification',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], default='email', max_length=20, verbose_name='Type de notification'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Template actif'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom du template'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='sujet',
            field=models.CharField(max_length=200, verbose_name='Sujet (pour emails)'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type_notification',
            field=models.CharField(choices=[('cotisation_due', 'Nouvelle cotisation due'), ('rappel_retard', 'Rappel de retard'), ('confirmation_paiement', 'Confirmation de paiement'), ('bienvenue', 'Message de bienvenue'), ('assemblage_generale', 'Convocation assemblée générale'), ('maintenance', 'Avis de maintenance'), ('personnalise', 'Message personnalisé')], max_length=30, verbose_name='Type de notification'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['association', 'statut'], name='iltizem_not_associa_63e2ca_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['destinataire', 'date_envoi'], name='iltizem_not_destina_0d42ce_idx'),
        ),
    ]
